- name: Container is running
  docker:
    name: registrator
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ ansible_hostname }}"
    command: -ip {{ facter_ipaddress_eth1 }} consul://{{ facter_ipaddress_eth1 }}:8500
  tags: [registrator]
