configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml" },
  { src: "node.xml", dir: "/data/jenkins/nodes/node-1", file: "config.xml", ip: "10.100.199.201", node_name: "node-1" },
  { src: "node.xml", dir: "/data/jenkins/nodes/node-2", file: "config.xml", ip: "10.100.199.202", node_name: "node-2" },
  { src: "node.xml", dir: "/data/jenkins/nodes/node-3", file: "config.xml", ip: "10.100.199.203", node_name: "node-3" },
  { src: "books-ms-docker-config.xml", dir: "/data/jenkins/jobs/books-ms", file: "config.xml" }
]

plugins:
 - docker-custom-build-environment