- name: Packages are installed
  apt:
    name: "{{ item }}"
  with_items: packages
  tags: [cje]

- name: Directory is created
  file:
    path: /data/jenkins_slave
    owner: vagrant
    state: directory
  tags: [cje]

- name: DB directory is created
  file:
    path: /data/jenkins_slave/workspace/books-ms-build/db
    recurse: yes
    mode: 0777
    state: directory
  tags: [cje]